feat: add support for custom unary, binary and ternary operators
charsleysa/node-sql-ts pull request #9
Opened 2022-06-05 07:21 UTC by hstanford

Adds a generic 'op' method to support operators that currently have no explicit method in node-sql-ts.

Syntax is:
```
Foo.baz.op('||+')(1)
```
which produces

```
"foo"."baz" ||+ 1
```
This also supports custom unary and ternary operators as
```
Foo.baz.op('IS EMPTY')()
"foo"."baz" IS EMPTY
```
and
```
Foo.baz.op('CAST', 'DEFAULT')('text', 'abcde')
"foo"."baz" CAST 'text' DEFAULT 'abcde'
```

This also adds a `preOp` method for custom prefix unary operators.

2022-06-05 07:25 UTC, hstanford commented
Thanks for converting this repo to typescript, massive amount of really valuable work! This is a rewrite of a PR I submitted to the base repo back in 2017, never got pulled as it went unmaintained.

I wanted to check about linting and prettier - I didn't end up running prettier on valueExpression.ts as it changed lines I hadn't touched. What would you like me to do here?

2022-06-09 02:33 UTC, charsleysa commented
Hi @hstanford 

Thanks for the contribution and sorry for not getting to this sooner!

I'd just like to clarify the use case for having a generic function like this vs adding more named operator functions.

Also, I'm not a fan of the `op` function returning another function that you need to call, I think it would be better if it could all be done as a single call, maybe using arrays like the `case` function.

Please let me know your thoughts.

2022-06-09 08:28 UTC, hstanford commented
No worries, thanks for the response!

My background is postgres, which has a large number of operators which aren't shared with other dialects. There is also support for creating your own operators, so we will never be able to cover all of them as named operator functions in this library. 

I think eventually it would be nice for consumers of this library to have the ability to extend the functions and operators it supports when it's first loaded in, and then not declare these at "runtime". `sql.addFunction`/`sql.addOperator` or similar. Unfortunately, the way the operators are mixed in makes this very difficult (even more so with typescript!), and I thought the design in this PR might bridge the gap.

My thinking when making the `op` function return another function was that I'd want `col.equals` to behave exactly the same as `col.op('=')`. It would line up with the behaviour of `sql.function`, which I think's appropriate considering that operators are just syntactic sugar for functions. It might also allow a user to mix in their own stuff - e.g. something along the lines of `Column.prototype.tsMatches = function () {return this.op('<->')}` in the pre-typescript world.

I'm ultimately happy to defer to your preference - the `case`-like syntax would still provide the functionality - but I think the design here makes it easier and more natural to read and write expressions.

2022-06-09 09:48 UTC, charsleysa commented
Thanks for the info!

I understand about the use case of user defined operators in sql. I actually didn't know you could do that so I learned something new today!

In regards to wanting to do something like `sql.function`, I would want to expose it in a similar way instead of adding it to the value expression mixin.

E.g. `const myOp = sql.operator('binary', '||+'); myOp(column, 1);`

Then you could also do `Column.prototype.myOp = function (right) { return myOp(this, right); }`

If you're still wanting to add it to the value expression mixin, to avoid returning another function that needs to be called, how about having an op function for each type?

E.g. `prefixUnaryOp(op), postfixUnaryOp(op), binaryOp(op, right), ternaryOp(op, middle, right)`

This would allow custom operators while only using a single function call, with the added bonus of being a bit more explicit in what kind of operator it is.

2022-06-09 12:41 UTC, hstanford commented
I really like those ideas - I'll reimplement like `const myOp = sql.operator('binary', '||+'); myOp(column, 1);`, and add the explicit operators to the mixin

2022-06-12 10:41 UTC, hstanford commented
The new implementation is pushed and I've updated the descriptive comment above :)

2022-06-13 03:36 UTC, charsleysa requested changes
As noted in the comments, value expression operators are negatively impacted.

My recommendation would be to separate the implementations, leave the `xxMethod` functions as they were and implement the `xxOperator` value expressions similar to the `cast` and `slice` implementations.

I would even go as a far as having a separate implementation for the `sql.xxOperator` functions so that there isn't a direct dependency on value expressions.

2022-06-13 03:36 UTC, charsleysa commented on lib/node/valueExpression.ts
> +        return prefixUnaryOperator(operator)(this)
This creates a new function every time a prefix unary operator is called which would impact performance if the operator is called in a loop

2022-06-13 03:36 UTC, charsleysa commented on lib/node/valueExpression.ts
> +        return postfixUnaryOperator(operator)(this)
This creates a new function every time a postfix unary operator is called which would impact performance if the operator is called in a loop

2022-06-13 03:36 UTC, charsleysa commented on lib/node/valueExpression.ts
> +        return binaryOperator(operator)(this, right);
This creates a new function every time a binary operator is called which would impact performance if the operator is called in a loop

2022-06-13 03:36 UTC, charsleysa commented on lib/node/valueExpression.ts
> +        return ternaryOperator(operator, separator)(this, middle, right);
This creates a new function every time a ternary operator is called which would impact performance if the operator is called in a loop

2022-06-13 05:26 UTC, hstanford commented
Nice catches and recommendations - I've separated the implementations so the global ones live in their own file and the mixins are implemented like cast/slice.

2022-06-13 07:33 UTC, charsleysa approved these changes
LGTM

2022-06-13 07:34 UTC, merged

2022-06-13 07:34 UTC, charsleysa commented
Thanks for the contribution!

2022-06-14 01:47 UTC, charsleysa commented
@hstanford this has been included in v6.2.0